services:
  - type: web
    name: plai-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: DATABASE_URL
        sync: false
